USE PRESCRICAO_MEDICAMENTOS
GO
CREATE SCHEMA PRESCRICAO_MEDICAMENTOS;
GO

CREATE TABLE PRESCRICAO_MEDICAMENTOS.MEDICO(
	NUMERO_IDENTIFICACAO			INT,
	NOME							NVARCHAR(20),
	ESPECIALIDADE					NVARCHAR(20),
	
	CONSTRAINT PK_MEDICO PRIMARY KEY (NUMERO_IDENTIFICACAO)
);
CREATE TABLE PRESCRICAO_MEDICAMENTOS.PACIENTE(
	NUMERO_UTENTE		INT,
	NOME				NVARCHAR(100),
	INFO_NASCIMENTO		DATE,
	ENDERECO			NVARCHAR(100),
	
	CONSTRAINT PK_PACIENTE PRIMARY KEY (NUMERO_UTENTE)
);
CREATE TABLE PRESCRICAO_MEDICAMENTOS.FARMACIA(
	NOME				NVARCHAR(20),
	TELEFONE			INT,
	ENDERECO			NVARCHAR(30),
	
	CONSTRAINT PK_FARMACIA PRIMARY KEY(NOME)
);
CREATE TABLE PRESCRICAO_MEDICAMENTOS.FARMACEUTICA(
	NUMERO_REGISTO_NACIONAL	INT,
	NOME					NVARCHAR(20),
	ENDERECO				NVARCHAR(100),
	
	CONSTRAINT PK_FARMACEUTICA PRIMARY KEY (NUMERO_REGISTO_NACIONAL)
);
CREATE TABLE PRESCRICAO_MEDICAMENTOS.FARMACO(
	NUMERO_REGISTO_NACIONAL_FARMACEUTICA	INT,
	NOME_COMERCIAL							NVARCHAR(20),
	FORMULA									NVARCHAR(30),
	
	CONSTRAINT PK_FARMACO PRIMARY KEY (NOME_COMERCIAL,NUMERO_REGISTO_NACIONAL_FARMACEUTICA),
	UNIQUE (NOME_COMERCIAL),
	CONSTRAINT FK_REGISTO_NACIONAL FOREIGN KEY(NUMERO_REGISTO_NACIONAL_FARMACEUTICA) REFERENCES PRESCRICAO_MEDICAMENTOS.FARMACEUTICA(NUMERO_REGISTO_NACIONAL)
);

CREATE TABLE PRESCRICAO_MEDICAMENTOS.PRESCRICAO(
	NUMERO					INT,
	NUM_UTENTE_PACIENTE		INT,
	ID_MEDICO				INT,
	NOME_FARMACIA			NVARCHAR(20),
	DATA_PROCESSAMENTO		DATE,
	
	CONSTRAINT PK_PRESCRICAO PRIMARY KEY (NUMERO),
	CONSTRAINT FK_PRESCRICAO1 FOREIGN KEY(ID_MEDICO) REFERENCES PRESCRICAO_MEDICAMENTOS.MEDICO(NUMERO_IDENTIFICACAO),
	CONSTRAINT FK_PRESCRICAO2 FOREIGN KEY(NUM_UTENTE_PACIENTE) REFERENCES PRESCRICAO_MEDICAMENTOS.PACIENTE(NUMERO_UTENTE),
	CONSTRAINT FK_PRESCRICAO3 FOREIGN KEY(NOME_FARMACIA) REFERENCES PRESCRICAO_MEDICAMENTOS.FARMACIA(NOME)
);

CREATE TABLE PRESCRICAO_MEDICAMENTOS.PRESC_FARMACO(
	NUM_PRESCRICAO			INT,
	NUM_REGISTO_FARM		INT,
	NOME_FARMACO			NVARCHAR(20),
	
	CONSTRAINT PK_PRESC_FARMACO PRIMARY KEY (NUM_PRESCRICAO, NOME_FARMACO),
	CONSTRAINT FK_PRESC_FARMACO1 FOREIGN KEY(NUM_PRESCRICAO) REFERENCES PRESCRICAO_MEDICAMENTOS.PRESCRICAO(NUMERO),
	CONSTRAINT FK_PRESC_FARMACO2 FOREIGN KEY(NOME_FARMACO) REFERENCES PRESCRICAO_MEDICAMENTOS.FARMACO(NOME_COMERCIAL)
);