DROP TABLE IF EXISTS RESERVA_DE_VOOS.AIRPORT;
DROP TABLE IF EXISTS RESERVA_DE_VOOS.AIRPLANE_TYPE;
DROP TABLE IF EXISTS RESERVA_DE_VOOS.AIRPLANE;
DROP TABLE IF EXISTS RESERVA_DE_VOOS.CAN_LAND;
DROP TABLE IF EXISTS RESERVA_DE_VOOS.FLIGHT;
DROP TABLE IF EXISTS RESERVA_DE_VOOS.FLIGHT_LEG;
DROP TABLE IF EXISTS RESERVA_DE_VOOS.FARE;
DROP TABLE IF EXISTS RESERVA_DE_VOOS.LEG_INSTANCE;
DROP TABLE IF EXISTS RESERVA_DE_VOOS.SEAT;
GO
DROP SCHEMA IF EXISTS RESERVA_DE_VOOS;
GO