use p2g6
GO
CREATE SCHEMA CONFERENCIAS;
GO

CREATE TABLE CONFERENCIAS.CONFERENCIA(
IDENTIFICACAO		NVARCHAR(20) NOT NULL,

CONSTRAINT PK_CONFERENCIA
	PRIMARY KEY (IDENTIFICACAO),
);

CREATE TABLE CONFERENCIAS.PARTICIPANTES(
MORADA						NVARCHAR(20) NOT NULL,
NOME						NVARCHAR(10) NOT NULL,
INFO_DATA_INSCRICAO			DATE NOT NULL,
EMAIL						NVARCHAR(30) NOT NULL,
IDENTIFICACAO_CONFERENCIA	NVARCHAR(20) NOT NULL,

CONSTRAINT PK_PARTICIPANTES
	PRIMARY KEY (EMAIL),
CONSTRAINT FK_PRESCRICAO
	FOREIGN KEY (IDENTIFICACAO_CONFERENCIA) REFERENCES CONFERENCIAS.CONFERENCIA(IDENTIFICACAO),
);

CREATE TABLE CONFERENCIAS.INSTITUICAO(
NOME		NVARCHAR(10) NOT NULL,
ENDERECO	NVARCHAR(30) NOT NULL,

CONSTRAINT PK_INSTITUICAO
	PRIMARY KEY (NOME),
);

CREATE TABLE CONFERENCIAS.AUTORES(
EMAIL				NVARCHAR(30) NOT NULL,
NOME				NVARCHAR(10) NOT NULL,
NOME_INSTITUICAO	NVARCHAR(10) NOT NULL,

CONSTRAINT PK_AUTORES
	PRIMARY KEY (EMAIL),
CONSTRAINT FK_AUTORES
	FOREIGN KEY (NOME_INSTITUICAO) REFERENCES CONFERENCIAS.INSTITUICAO(NOME),
);

CREATE TABLE CONFERENCIAS.ARTIGO_CIENTIFICO(
TITULO						NVARCHAR(20) NOT NULL,
NUMERO_REGISTO				INT NOT NULL CHECK(NUMERO_REGISTO>0),
IDENTIFICACAO_CONFERENCIA	NVARCHAR(20) NOT NULL,

CONSTRAINT PK_ARTIGO_CIENTIFICO
	PRIMARY KEY (NUMERO_REGISTO),
CONSTRAINT FK_ARTIGO_CIENTIFICO
	FOREIGN KEY (IDENTIFICACAO_CONFERENCIA) REFERENCES CONFERENCIAS.CONFERENCIA(IDENTIFICACAO),
);

CREATE TABLE CONFERENCIAS.TEM(
EMAIL_AUTORES							NVARCHAR(30) NOT NULL,
NUMERO_REGISTO_ARTIGO_CIENTIFICO		INT NOT NULL CHECK(NUMERO_REGISTO_ARTIGO_CIENTIFICO>0),

CONSTRAINT PK_TEM
	PRIMARY KEY (EMAIL_AUTORES, NUMERO_REGISTO_ARTIGO_CIENTIFICO),
CONSTRAINT FK_TEM
	FOREIGN KEY (EMAIL_AUTORES) REFERENCES CONFERENCIAS.AUTORES(EMAIL),
	FOREIGN KEY (NUMERO_REGISTO_ARTIGO_CIENTIFICO) REFERENCES CONFERENCIAS.ARTIGO_CIENTIFICO(NUMERO_REGISTO),
);



CREATE TABLE CONFERENCIAS.COMPROVATIVO(
ASSINATURA					NVARCHAR(10) NOT NULL,
NOME_INSTITUICAO			NVARCHAR(10) NOT NULL,

CONSTRAINT PK_COMPROVATIVO
	PRIMARY KEY (ASSINATURA),
CONSTRAINT FK_COMPROVATIVO
	FOREIGN KEY (NOME_INSTITUICAO) REFERENCES CONFERENCIAS.INSTITUICAO(NOME),
);

CREATE TABLE CONFERENCIAS.REFERENCIA_TRANSACAO(
VALOR			INT NOT NULL CHECK(VALOR>0),

CONSTRAINT PK_TRANSACAO
	PRIMARY KEY (VALOR)
);

CREATE TABLE CONFERENCIAS.ESTUDANTE(
EMAIL_PARTICIPANTE			NVARCHAR(30) NOT NULL,
INFO_DATA_INSCRICAO			DATE NOT NULL,
MORADA						NVARCHAR(20) NOT NULL,
NOME						NVARCHAR(10) NOT NULL,
NOME_INSTITUICAO			NVARCHAR(10) NOT NULL,
ASSINATURA_COMPROVATIVO		NVARCHAR(10) NOT NULL,

CONSTRAINT PK_ESTUDANTE
	PRIMARY KEY (EMAIL_PARTICIPANTE),
CONSTRAINT FK_ESTUDANTE
	FOREIGN KEY (EMAIL_PARTICIPANTE) REFERENCES CONFERENCIAS.PARTICIPANTES(EMAIL),
	FOREIGN KEY (NOME_INSTITUICAO) REFERENCES CONFERENCIAS.INSTITUICAO(NOME),
	FOREIGN KEY (ASSINATURA_COMPROVATIVO) REFERENCES CONFERENCIAS.COMPROVATIVO(ASSINATURA),

);

CREATE TABLE CONFERENCIAS.NAO_ESTUDANTE(
EMAIL_PARTICIPANTE			NVARCHAR(30) NOT NULL,
INFO_DATA_INSCRICAO			DATE NOT NULL,
MORADA						NVARCHAR(20) NOT NULL,
NOME						NVARCHAR(10) NOT NULL,
VALOR						INT NOT NULL CHECK(VALOR>0),

CONSTRAINT PK_NAO_ESTUDANTE
	PRIMARY KEY (EMAIL_PARTICIPANTE),
CONSTRAINT FK_NAO_ESTUDANTE
	FOREIGN KEY (EMAIL_PARTICIPANTE) REFERENCES CONFERENCIAS.PARTICIPANTES(EMAIL),
	FOREIGN KEY (VALOR) REFERENCES CONFERENCIAS.REFERENCIA_TRANSACAO(VALOR),
);





CREATE TABLE CONFERENCIAS.SISTEMA_INFORMACAO(
ASSINATURA_COMPROVATIVO NVARCHAR(10) NOT NULL,
LOCALIZACAO NVARCHAR(20) NOT NULL,
PALAVRA_CHAVE NVARCHAR(16) NOT NULL,
CONSTRAINT PK_SISTEMA_INFORMACAO
	PRIMARY KEY (PALAVRA_CHAVE),
CONSTRAINT FK_SISTEMA_INFORMACAO
	FOREIGN KEY (ASSINATURA_COMPROVATIVO) REFERENCES CONFERENCIAS.COMPROVATIVO(ASSINATURA),
);

