USE p2g6;
GO
CREATE SCHEMA ATL;
GO

CREATE TABLE ATL.TURMA(
	ID					NVARCHAR(20) NOT NULL,
	num_max_alunos		INT NOT NULL CHECK(num_max_alunos>0),
	designacao			NVARCHAR(100) NOT NULL,	
	CC_prof				VARCHAR(12) NOT NULL,

	CONSTRAINT PK_TURMA PRIMARY KEY(ID)
);

CREATE TABLE ATL.PROFESSOR(
	num_CC					VARCHAR(12) NOT NULL,
	num_func				NVARCHAR(12) NOT NULL,
	identificador_turma		NVARCHAR(20) NOT NULL,

	CONSTRAINT PK_CC_PROFESSOR PRIMARY KEY(num_CC),
	CONSTRAINT FK_PROFESSOR_TURMA FOREIGN KEY(identificador_turma) REFERENCES ATL.TURMA(ID)
);


CREATE TABLE ATL.ALUNO(
	num_CC			VARCHAR(12) NOT NULL,
	nome			NVARCHAR(100) NOT NULL,
	morada			NVARCHAR(100) NOT NULL,	
	data_nasc		DATE NOT NULL,
	telefone		VARCHAR(12),
	email			NVARCHAR(100) NOT NULL,
	CC_enc_educ		VARCHAR(12) NOT NULL,
	ID_turma		NVARCHAR(20) NOT NULL,

	CONSTRAINT PK_ALUNO PRIMARY KEY(num_CC),
	CONSTRAINT FK_ALUNO_ID FOREIGN KEY(ID_turma) REFERENCES ATL.TURMA(ID)
);

CREATE TABLE ATL.ENC_EDUCACAO(
	num_CC			VARCHAR(12) NOT NULL,
	num_CC_aluno	VARCHAR(12) NOT NULL,

	CONSTRAINT PK_ENC_EDUCACAO_CC PRIMARY KEY(num_CC),
	CONSTRAINT FK_ENC_EDUCACAO_ALUNO FOREIGN KEY(num_CC_aluno) REFERENCES ATL.ALUNO(num_CC)
);

CREATE TABLE ATL.PESSOA(
	num_CC		VARCHAR(12) NOT NULL,
	nome			NVARCHAR(100) NOT NULL,
	email			NVARCHAR(100) NOT NULL,
	telefone		VARCHAR(12),
	morada			NVARCHAR(100) NOT NULL,
	data_nasc		DATE  NOT NULL,
	CONSTRAINT PK_PESSOA PRIMARY KEY(num_cc),
	CONSTRAINT FK_PESSOA_ENC_EDUC FOREIGN KEY(num_CC) REFERENCES ATL.ENC_EDUCACAO(num_CC),
	CONSTRAINT FK_PESSOA_PROFESSOR FOREIGN KEY(num_CC) REFERENCES ATL.PROFESSOR(num_CC)
);

CREATE TABLE ATL.ENTREGAR_LEVANTAR_ALUNOS(
num_cc_aluno		VARCHAR(12) NOT NULL,
num_cc_pessoa		VARCHAR(12) NOT NULL,
autorizado			VARCHAR(2) NOT NULL,

CONSTRAINT PK_ENTREGAR_LEVANTAR_ALUNOS PRIMARY KEY(num_cc_aluno,num_cc_pessoa),
CONSTRAINT FK_CC_ALUNO FOREIGN KEY(num_cc_aluno) REFERENCES ATL.ALUNO(num_CC),
CONSTRAINT FK_CC_PESSOA FOREIGN KEY(num_cc_pessoa) REFERENCES ATL.PESSOA(num_CC)
);


CREATE TABLE ATL.PERTENCE(
ID_turma		NVARCHAR(20) NOT NULL,
escolaridade	INT NOT NULL CHECK(escolaridade>0),

CONSTRAINT PK_PERTENCE_CLASSE PRIMARY KEY(escolaridade),
CONSTRAINT FK_PERTENCE_ID FOREIGN KEY(ID_turma) REFERENCES ATL.TURMA(ID)
);

CREATE TABLE ATL.ESCOLARIDADE(
	classe			INT NOT NULL CHECK(classe>0),

	CONSTRAINT PK_ESCOLARIDADE PRIMARY KEY(classe),
	CONSTRAINT FK_ESCOLARIDADE FOREIGN KEY(classe) REFERENCES ATL.PERTENCE(escolaridade)
);

CREATE TABLE ATL.ATIVIDADE(
	ID				NVARCHAR(20) NOT NULL,
	custo			INT NOT NULL CHECK(custo>0),
	designacao		NVARCHAR(100),	

	CONSTRAINT PK_ATIVIDADE PRIMARY KEY(ID)
);

CREATE TABLE ATL.TEM(
	ID_atividade		NVARCHAR(20) NOT NULL,
	ID_turma			NVARCHAR(20) NOT NULL,

	CONSTRAINT PK_TEM PRIMARY KEY(ID_atividade, ID_turma),
	CONSTRAINT FK_ATIVIDADE FOREIGN KEY(ID_atividade) REFERENCES ATL.ATIVIDADE(ID),
	CONSTRAINT FK_TURMA FOREIGN KEY(ID_turma) REFERENCES ATL.TURMA(ID)
);

CREATE TABLE ATL.PAGAMENTOS(
outras_atividades		NVARCHAR(20),
despesas_casa			INT NOT NULL,
mensalidade				INT NOT NULL,

CONSTRAINT PK_PAGAMENTOS_MENSALIDADE PRIMARY KEY(mensalidade),
);


CREATE TABLE ATL.EFETUA(
desconto_familia		INT NOT NULL CHECK (desconto_familia>0),
num_CC_ENC				VARCHAR(12) NOT NULL,
mensalidade_pagamentos	INT NOT NULL CHECK(mensalidade_pagamentos>0),

CONSTRAINT PK_EFETUA_NUM_CC_ENC PRIMARY KEY(num_CC_ENC,mensalidade_pagamentos),
CONSTRAINT FK_EFETUA_NUM_CC_ENC FOREIGN KEY(num_CC_ENC) REFERENCES ATL.ENC_EDUCACAO(num_CC),
CONSTRAINT FK_EFETUA_MENSALIDADE FOREIGN KEY(mensalidade_pagamentos) REFERENCES ATL.PAGAMENTOS(mensalidade)

);