DROP TABLE IF EXISTS MODULO_ENCOMENDAS.EMPRESA;
DROP TABLE IF EXISTS MODULO_ENCOMENDAS.PRODUTO;
DROP TABLE IF EXISTS MODULO_ENCOMENDAS.ENCOMENDA;
DROP TABLE IF EXISTS MODULO_ENCOMENDAS.FORNECEDOR;
DROP TABLE IF EXISTS MODULO_ENCOMENDAS.TIPO_FORNECEDOR;
DROP TABLE IF EXISTS MODULO_ENCOMENDAS.FORNECE;
DROP TABLE IF EXISTS MODULO_ENCOMENDAS.CONTEM;
GO
DROP SCHEMA IF EXISTS MODULO_ENCOMENDAS;
GO
