DROP TABLE IF EXISTS RENT_A_CAR.ALUGUER;
DROP TABLE IF EXISTS RENT_A_CAR.BALCAO;
DROP TABLE IF EXISTS RENT_A_CAR.CLIENTE;
DROP TABLE IF EXISTS RENT_A_CAR.VEICULO;
DROP TABLE IF EXISTS RENT_A_CAR.LIGEIROS;
DROP TABLE IF EXISTS RENT_A_CAR.PESADOS;
DROP TABLE IF EXISTS RENT_A_CAR.SIMILARIDADE;
DROP TABLE IF EXISTS RENT_A_CAR.TIPO_VEICULO;
GO
DROP SCHEMA IF EXISTS RENT_A_CAR;
GO