// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkXdA5VGyYU-OxTKFuLVPrP99caeuEm70',
    appId: '1:537054634839:web:60b7cf9238c25dd5e09412',
    messagingSenderId: '537054634839',
    projectId: 'peci-sgd',
    authDomain: 'peci-sgd.firebaseapp.com',
    storageBucket: 'peci-sgd.appspot.com',
    measurementId: 'G-VCMFZ4HMM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe5YfELF08QNkzzhZjTH3a-R3J-Qt_dcs',
    appId: '1:537054634839:android:bba87f3aac3132aee09412',
    messagingSenderId: '537054634839',
    projectId: 'peci-sgd',
    storageBucket: 'peci-sgd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaARUk0A7ybDNKLAebTvg2jkOfS_htZJc',
    appId: '1:537054634839:ios:a28c14e5fff26e2ce09412',
    messagingSenderId: '537054634839',
    projectId: 'peci-sgd',
    storageBucket: 'peci-sgd.appspot.com',
    iosClientId: '537054634839-2epdmckefsdft9phs2ib1a8v0gos2ldl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ssdFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaARUk0A7ybDNKLAebTvg2jkOfS_htZJc',
    appId: '1:537054634839:ios:a28c14e5fff26e2ce09412',
    messagingSenderId: '537054634839',
    projectId: 'peci-sgd',
    storageBucket: 'peci-sgd.appspot.com',
    iosClientId: '537054634839-2epdmckefsdft9phs2ib1a8v0gos2ldl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ssdFrontend',
  );
}
