DROP TABLE IF EXISTS ATL.ENTREGAR_LEVANTAR_ALUNOS;
DROP TABLE IF EXISTS ATL.PESSOA;
DROP TABLE IF EXISTS ATL.PROFESSOR;
DROP TABLE IF EXISTS ATL.ENC_EDUCACAO;
DROP TABLE IF EXISTS ATL.ALUNO;
DROP TABLE IF EXISTS ATL.PERTENCE;
DROP TABLE IF EXISTS ATL.TURMA;
DROP TABLE IF EXISTS ATL.TEM;
DROP TABLE IF EXISTS ATL.ATIVIDADE;
DROP TABLE IF EXISTS ATL.ESCOLARIDADE;
DROP TABLE IF EXISTS ATL.ATIVIDADE;
DROP TABLE IF EXISTS ATL.PAGAMENTOS;
DROP TABLE IF EXISTS ATL.EFETUA;
GO
DROP SCHEMA IF EXISTS ATL;