DROP TABLE IF EXISTS CONFERENCIAS.PARTICIPANTES;
DROP TABLE IF EXISTS CONFERENCIAS.CONFERENCIA;
DROP TABLE IF EXISTS CONFERENCIAS.INSTITUICAO;
DROP TABLE IF EXISTS CONFERENCIAS.AUTORES;
DROP TABLE IF EXISTS CONFERENCIAS.ESTUDANTE;
DROP TABLE IF EXISTS CONFERENCIAS.NAO_ESTUDANTE;
DROP TABLE IF EXISTS CONFERENCIAS.REFERENCIA_TRANSACAO;
DROP TABLE IF EXISTS CONFERENCIAS.TEM;
DROP TABLE IF EXISTS CONFERENCIAS.ARTIGO_CIENTIFICO;
DROP TABLE IF EXISTS CONFERENCIAS.COMPROVATIVO;
DROP TABLE IF EXISTS CONFERENCIAS.SISTEMA_INFORMACAO;
GO
DROP SCHEMA IF EXISTS CONFERENCIAS;
GO