use p2g6
GO
CREATE SCHEMA PRESCRICAO_MEDICAMENTOS;
GO

CREATE TABLE PRESCRICAO_MEDICAMENTOS.PACIENTE(
NOME				NVARCHAR(10) NOT NULL,
INFO_NASCIMENTO		NVARCHAR(8) NOT NULL,
NUMERO_UTENTE		INT NOT NULL CHECK(NUMERO_UTENTE>0),
ENDERECO			NVARCHAR(30) NOT NULL,

CONSTRAINT PK_PACIENTE
	PRIMARY KEY (NUMERO_UTENTE)
);

CREATE TABLE PRESCRICAO_MEDICAMENTOS.MEDICO(
NUMERO_IDENTIFICACAO	INT NOT NULL CHECK(NUMERO_IDENTIFICACAO>0),
NOME					NVARCHAR(10) NOT NULL,
ESPECIALIDADE			NVARCHAR(10),

CONSTRAINT PK_MEDICO
	PRIMARY KEY(NUMERO_IDENTIFICACAO),
);

CREATE TABLE PRESCRICAO_MEDICAMENTOS.FARMACIA(
TELEFONE			INT NOT NULL CHECK(TELEFONE>0),
ENDERECO			NVARCHAR(30) NOT NULL,
NOME				NVARCHAR(10) NOT NULL,
NIF					INT NOT NULL CHECK(NIF>0),

CONSTRAINT PK_FARMACIA
	PRIMARY KEY (NIF),
);

CREATE TABLE PRESCRICAO_MEDICAMENTOS.PRESCRICAO(
INFO_DATA					DATE NOT NULL,
NUMERO_UNICO				INT NOT NULL CHECK(NUMERO_UNICO>0),
NUMERO_IDENTIFICACAO_MEDICO INT NOT NULL CHECK(NUMERO_IDENTIFICACAO_MEDICO>0),
NUMERO_UTENTE_PACIENTE		INT NOT NULL CHECK(NUMERO_UTENTE_PACIENTE>0),
NIF_FARMACIA				INT NOT NULL CHECK(NIF_FARMACIA>0),

CONSTRAINT PK_PRESCRICAO
	PRIMARY KEY (NUMERO_UNICO),
CONSTRAINT FK_PRESCRICAO
	FOREIGN KEY (NUMERO_IDENTIFICACAO_MEDICO) REFERENCES PRESCRICAO_MEDICAMENTOS.MEDICO(NUMERO_IDENTIFICACAO),
	FOREIGN KEY (NUMERO_UTENTE_PACIENTE) REFERENCES PRESCRICAO_MEDICAMENTOS.PACIENTE(NUMERO_UTENTE),
	FOREIGN KEY (NIF_FARMACIA) REFERENCES PRESCRICAO_MEDICAMENTOS.FARMACIA(NIF),
);

CREATE TABLE PRESCRICAO_MEDICAMENTOS.FARMACEUTICA(
NUMERO_REGISTO_NACIONAL		INT NOT NULL,
NOME						NVARCHAR(10) NOT NULL,
TELEFONE					INT NOT NULL CHECK(TELEFONE>0),
ENDERECO					NVARCHAR(30),

CONSTRAINT PK_FARMACEUTICA
	PRIMARY KEY (NUMERO_REGISTO_NACIONAL),
);

CREATE TABLE PRESCRICAO_MEDICAMENTOS.FARMACO(
NOME_COMERCIAL							NVARCHAR(10) NOT NULL,
FORMULA									NVARCHAR (20) NOT NULL,
NUMERO_REGISTO_NACIONAL_FARMACEUTICA	INT NOT NULL CHECK(NUMERO_REGISTO_NACIONAL_FARMACEUTICA>0),
NIF_FARMACIA							INT NOT NULL CHECK(NIF_FARMACIA>0),

CONSTRAINT PK_FARMACO
	PRIMARY KEY(NOME_COMERCIAL),
CONSTRAINT FK_FARMACO
	FOREIGN KEY(NUMERO_REGISTO_NACIONAL_FARMACEUTICA) REFERENCES PRESCRICAO_MEDICAMENTOS.FARMACEUTICA(NUMERO_REGISTO_NACIONAL),
	FOREIGN KEY(NIF_FARMACIA) REFERENCES PRESCRICAO_MEDICAMENTOS.FARMACIA(NIF),
);



CREATE TABLE PRESCRICAO_MEDICAMENTOS.TEM(
NUMERO_UNICO_PRESCRICAO			INT NOT NULL,
NOME_COMERCIAL_FARMACO			NVARCHAR(10) NOT NULL,

CONSTRAINT PK_TEM
	PRIMARY KEY (NUMERO_UNICO_PRESCRICAO, NOME_COMERCIAL_FARMACO),
CONSTRAINT FK_TEM
	FOREIGN KEY (NUMERO_UNICO_PRESCRICAO) REFERENCES PRESCRICAO_MEDICAMENTOS.PRESCRICAO(NUMERO_UNICO),
	FOREIGN KEY (NOME_COMERCIAL_FARMACO) REFERENCES PRESCRICAO_MEDICAMENTOS.FARMACO(NOME_COMERCIAL),
);










