DROP TABLE IF EXISTS PRESCRICAO_MEDICAMENTOS.PACIENTE;
DROP TABLE IF EXISTS PRESCRICAO_MEDICAMENTOS.PRESCRICAO;
DROP TABLE IF EXISTS PRESCRICAO_MEDICAMENTOS.MEDICO;
DROP TABLE IF EXISTS PRESCRICAO_MEDICAMENTOS.FARMACO;
DROP TABLE IF EXISTS PRESCRICAO_MEDICAMENTOS.FARMACEUTICA;
DROP TABLE IF EXISTS PRESCRICAO_MEDICAMENTOS.FARMACIA;
DROP TABLE IF EXISTS PRESCRICAO_MEDICAMENTOS.TEM;
GO
DROP SCHEMA IF EXISTS PRESCRICAO_MEDICAMENTOS;
GO