use p2g6
GO

CREATE SCHEMA RENT_A_CAR;
GO

CREATE TABLE RENT_A_CAR.CLIENTE(
	NIF			INT NOT NULL CHECK (NIF>0),
	NOME		NVARCHAR(20) NOT NULL,
	NUM_CARTA	INT,
	ENDERECO	NVARCHAR(30),
	CONSTRAINT PK_CLIENTE
		PRIMARY KEY (NIF),
);

CREATE TABLE RENT_A_CAR.BALCAO(
	NUMERO		INT NOT NULL CHECK (NUMERO>0),
	NOME		NVARCHAR(20),
	ENDERECO	NVARCHAR(30),
	CONSTRAINT PK_BALCAO
		PRIMARY KEY (NUMERO),
);
CREATE TABLE RENT_A_CAR.TIPO_VEICULO(
	DESIGNACAO		NVARCHAR(30),
	CODIGO			INT NOT NULL CHECK(CODIGO>0),
	AR_CONDICIONADO BIT,
	CONSTRAINT PK_TIPO_VEICULO
		PRIMARY KEY(CODIGO),

);

CREATE TABLE RENT_A_CAR.PESADOS(
	PESO			INT NOT NULL CHECK(PESO>0),
	PASSAGEIROS		INT NOT NULL CHECK(PASSAGEIROS>0),
	CODIGO			INT NOT NULL CHECK(CODIGO>0),

	CONSTRAINT PK_PESADO
		PRIMARY KEY(CODIGO),
	CONSTRAINT FK_CODIGO_PESADO 
		FOREIGN KEY(CODIGO) REFERENCES RENT_A_CAR.TIPO_VEICULO(CODIGO)
);

CREATE TABLE RENT_A_CAR.LIGEIROS(
	NUMLUGARES		INT NOT NULL CHECK(NUMLUGARES>0),
	PORTAS			INT NOT NULL CHECK(PORTAS>0),
	COMBUSTIVEL		NVARCHAR(30),
	CODIGO			INT NOT NULL CHECK(CODIGO>0),

	CONSTRAINT PK_LIGEIRO
		PRIMARY KEY(CODIGO),
	CONSTRAINT FK_CODIGO_LIGEIRO 
		FOREIGN KEY(CODIGO) REFERENCES RENT_A_CAR.TIPO_VEICULO(CODIGO)
);

CREATE TABLE RENT_A_CAR.VEICULO(
	MATRICULA			NCHAR(10),
	MARCA				NVARCHAR(30),
	ANO					INT NOT NULL CHECK(ANO>0),
	CODIGO_TIPO_VEICULO INT NOT NULL CHECK(CODIGO_TIPO_VEICULO>0),

	CONSTRAINT PK_VEICULO
		PRIMARY KEY (MATRICULA),
	CONSTRAINT FK_CODIGO 
		FOREIGN KEY (CODIGO_TIPO_VEICULO) REFERENCES RENT_A_CAR.TIPO_VEICULO(CODIGO)

);

CREATE TABLE RENT_A_CAR.SIMILARIDADE(
CODIGO_1		INT NOT NULL CHECK(CODIGO_1>0),
CODIGO_2		INT NOT NULL CHECK(CODIGO_2>0),

CONSTRAINT PK_SIMILARIDADE
	PRIMARY KEY(CODIGO_1,CODIGO_2),
CONSTRAINT FK_CODIGO_TIPO_SIMILARIDADE
	FOREIGN KEY(CODIGO_1) REFERENCES RENT_A_CAR.TIPO_VEICULO(CODIGO),
	FOREIGN KEY(CODIGO_2) REFERENCES RENT_A_CAR.TIPO_VEICULO(CODIGO)
);

CREATE TABLE RENT_A_CAR.ALUGUER(
	NUMERO			INT NOT NULL CHECK(NUMERO>0),
	DURACAO			INT NOT NULL CHECK(DURACAO>0),
	DATA_ALUGUER	DATE NOT NULL,
	MATRICULA		NCHAR(10) NOT NULL,
	NUMERO_BALCAO	INT NOT NULL CHECK(NUMERO_BALCAO>0),
	NIF				INT NOT NULL CHECK(NIF>0),

	CONSTRAINT PK_ALUGUER
		PRIMARY KEY (NUMERO),
	CONSTRAINT FK_ALUGUER 
		FOREIGN KEY(NIF) REFERENCES RENT_A_CAR.CLIENTE(NIF),
		FOREIGN KEY(NUMERO_BALCAO) REFERENCES RENT_A_CAR.BALCAO(NUMERO),
		FOREIGN KEY(MATRICULA) REFERENCES RENT_A_CAR.VEICULO(MATRICULA),
);


