use p2g6
GO
CREATE SCHEMA MODULO_ENCOMENDAS;
GO

CREATE TABLE MODULO_ENCOMENDAS.EMPRESA(
CODIGO_IDENTIFICACAO		INT NOT NULL CHECK(CODIGO_IDENTIFICACAO>0),
NOME_EMPRESARIAL			VARCHAR(40) NOT NULL,
ENDERECO					VARCHAR(50) NOT NULL,
CONSTRAINT PK_EMPRESA
	PRIMARY KEY(CODIGO_IDENTIFICACAO),
);

CREATE TABLE MODULO_ENCOMENDAS.PRODUTO(
TAXA_IVA						INT NOT NULL CHECK (TAXA_IVA>=0),
PRECO							MONEY CHECK(PRECO>=0),
NOME							VARCHAR(50) NOT NULL,
CODIGO							VARCHAR(50) NOT NULL,
CODIGO_IDENTIFICACAO_EMPRESA	INT NOT NULL CHECK(CODIGO_IDENTIFICACAO_EMPRESA>0),
NUMERO_UNIDADES_ARMAZEM			INT CHECK(NUMERO_UNIDADES_ARMAZEM>=0),

CONSTRAINT PK_PRODUTO
	PRIMARY KEY(CODIGO),
CONSTRAINT FK_CODIGO_IDENTIFICACAO_EMPRESA 
	FOREIGN KEY(CODIGO_IDENTIFICACAO_EMPRESA) REFERENCES MODULO_ENCOMENDAS.EMPRESA(CODIGO_IDENTIFICACAO)
);

CREATE TABLE MODULO_ENCOMENDAS.FORNECEDOR(
NUMERO_FAX				VARCHAR(12) NOT NULL, 
NOME					NVARCHAR(30) NOT NULL,
NIF						INT NOT NULL CHECK(NIF>0),
CONDICOES_PAGAMENTO		VARCHAR(30) NOT NULL,
ENDERECO				VARCHAR(20) NOT NULL,

CONSTRAINT PK_FORNECEDOR
	PRIMARY KEY(NIF),
);


CREATE TABLE MODULO_ENCOMENDAS.ENCOMENDA(
NUMERO_ENCOMENDA		INT NOT NULL,
DATA_ENCOMENDA			DATE NOT NULL, 
NIF_FORNECEDOR			INT NOT NULL CHECK(NIF_FORNECEDOR>0),
CODIGO_PRODUTO			VARCHAR(50),

CONSTRAINT PK_ENCOMENDA
	PRIMARY KEY(NUMERO_ENCOMENDA),
CONSTRAINT FK_ENCOMENDA
	FOREIGN KEY(CODIGO_PRODUTO) REFERENCES MODULO_ENCOMENDAS.PRODUTO(CODIGO),
	FOREIGN KEY(NIF_FORNECEDOR) REFERENCES MODULO_ENCOMENDAS.FORNECEDOR(NIF),
);





CREATE TABLE MODULO_ENCOMENDAS.TIPO_FORNECEDOR(
CODIGO_INTERNO			INT NOT NULL CHECK(CODIGO_INTERNO>0),
DESIGNACAO				INT NOT NULL CHECK(DESIGNACAO>0),
NIF_FORNECEDOR			INT NOT NULL CHECK(NIF_FORNECEDOR>0),

CONSTRAINT PK_TIPO_FORNECEDOR
	PRIMARY KEY(CODIGO_INTERNO),
CONSTRAINT FK_TIPO_FORNECEDOR
		FOREIGN KEY(NIF_FORNECEDOR) REFERENCES MODULO_ENCOMENDAS.FORNECEDOR(NIF)
);



CREATE TABLE MODULO_ENCOMENDAS.FORNECE(
NIF_FORNECEDOR			INT NOT NULL CHECK(NIF_FORNECEDOR>0),
CODIGO_IDENTIFICACAO	INT NOT NULL CHECK(CODIGO_IDENTIFICACAO>0),

CONSTRAINT PK_FORNECE
	PRIMARY KEY(NIF_FORNECEDOR,CODIGO_IDENTIFICACAO),
CONSTRAINT FK_FORNCECE
	FOREIGN KEY (NIF_FORNECEDOR) REFERENCES MODULO_ENCOMENDAS.FORNECEDOR(NIF),
	FOREIGN KEY(CODIGO_IDENTIFICACAO) REFERENCES MODULO_ENCOMENDAS.EMPRESA(CODIGO_IDENTIFICACAO),
); 


CREATE TABLE MODULO_ENCOMENDAS.CONTEM(
QUANTIDADE				INT NOT NULL CHECK (QUANTIDADE>0),
CODIGO_PRODUTO			VARCHAR(50) NOT NULL,
NUMERO_DA_ENCOMENDA		INT NOT NULL CHECK(NUMERO_DA_ENCOMENDA>0),

CONSTRAINT PK_CONTEM
	PRIMARY KEY(CODIGO_PRODUTO,NUMERO_DA_ENCOMENDA),
CONSTRAINT FK_CONTEM
	FOREIGN KEY (CODIGO_PRODUTO) REFERENCES MODULO_ENCOMENDAS.PRODUTO(CODIGO),
	FOREIGN KEY (NUMERO_DA_ENCOMENDA) REFERENCES MODULO_ENCOMENDAS.ENCOMENDA(NUMERO_ENCOMENDA)
);