use p2g6
GO

CREATE SCHEMA ONLINEGAMES_PLATFORM;
GO

CREATE TABLE ONLINEGAMES_PLATFORM.Utilizador(
	Email			VARCHAR(30)			NOT NULL,
	Palavra_passe	VARCHAR(30)			NOT NULL,
	NIF				VARCHAR(30)			NOT NULL UNIQUE,
	
	CONSTRAINT PK_UTILIZADOR PRIMARY KEY(NIF)
);

CREATE TABLE ONLINEGAMES_PLATFORM.Vendedor(
	NR_ARTIGOS_VENDIDOS		INT,			
	IBAN					VARCHAR(30)	NOT NULL,
	NIF						VARCHAR(30) NOT NULL ,
	
	CONSTRAINT PK_VENDEDOR PRIMARY KEY (NIF),
	CONSTRAINT FK_VENDEDOR FOREIGN KEY(NIF) REFERENCES ONLINEGAMES_PLATFORM.UTILIZADOR(NIF) ON DELETE CASCADE ON UPDATE CASCADE,

);

CREATE TABLE ONLINEGAMES_PLATFORM.Comprador(
	MORADA				VARCHAR(50),			
	NIF					VARCHAR(30),
	CONSTRAINT PK_COMPRADOR PRIMARY KEY (NIF),
	CONSTRAINT FK_COMPRADOR FOREIGN KEY(NIF) REFERENCES ONLINEGAMES_PLATFORM.UTILIZADOR(NIF) ON DELETE CASCADE ON UPDATE CASCADE,

);


CREATE TABLE ONLINEGAMES_PLATFORM.GENERO(
	Nome				VARCHAR(30)		NOT NULL,
	CONSTRAINT PK_GENERO PRIMARY KEY(Nome)
);

CREATE TABLE ONLINEGAMES_PLATFORM.GENERO_PREFERIDO(
	NIF_Comprador		VARCHAR(30)		NOT NULL,
	Nome_Genero			VARCHAR(30)		NOT NULL,

	CONSTRAINT PK_GENERO_PREF PRIMARY KEY(NIF_Comprador,Nome_Genero),
	CONSTRAINT FK_GEN_PREF_USER FOREIGN KEY(NIF_Comprador) REFERENCES ONLINEGAMES_PLATFORM.Comprador(NIF) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_GEN_PREF_NOME FOREIGN KEY(Nome_Genero) REFERENCES ONLINEGAMES_PLATFORM.GENERO(Nome) ON DELETE CASCADE ON UPDATE CASCADE,
);


CREATE TABLE ONLINEGAMES_PLATFORM.ANUNCIOS(
	ID					INT				NOT NULL,
	Titulo				VARCHAR(50)		NOT NULL,
	Descricao			VARCHAR(1000),
	NIF_VENDEDOR		VARCHAR(30),
	
	CONSTRAINT PK_ANUNCIOS PRIMARY KEY(ID),
	CONSTRAINT FK_ANUNCIOS_VENDEDOR FOREIGN KEY(NIF_VENDEDOR) REFERENCES ONLINEGAMES_PLATFORM.VENDEDOR(NIF) ON DELETE SET NULL ON UPDATE CASCADE,
);

CREATE TABLE ONLINEGAMES_PLATFORM.PLATAFORMA(
	NOME_PLATAFORMA					VARCHAR(40) NOT NULL,
	DESCRICAO_PLATAFORMA			VARCHAR(200),
	

	CONSTRAINT PK_PLATAFORMA PRIMARY KEY(NOME_PLATAFORMA)
);

CREATE TABLE ONLINEGAMES_PLATFORM.JOGO(
	STOCK					INT	check (STOCK>=0),
	NOME					VARCHAR(100) NOT NULL,
	PRECO					INT NOT NULL CHECK(PRECO>0),
	DESCRICAO_JOGO			VARCHAR(1000),
	ANUNCIO_ID				INT not null,
	NOME_PLATAFORMA			VARCHAR(40),
	
	CONSTRAINT PK_JOGO PRIMARY KEY(NOME,ANUNCIO_ID),
	CONSTRAINT FK_JOGO FOREIGN KEY(NOME_PLATAFORMA) REFERENCES ONLINEGAMES_PLATFORM.PLATAFORMA(NOME_PLATAFORMA),
	CONSTRAINT FK_JOGO_ANUNCIO FOREIGN KEY(ANUNCIO_ID) REFERENCES ONLINEGAMES_PLATFORM.ANUNCIOS(ID),

);


CREATE TABLE ONLINEGAMES_PLATFORM.AVALIACAO_JOGO(
	NIF_COMPRADOR		VARCHAR(30) NOT NULL,
	NOME_JOGO			VARCHAR(100) NOT NULL,
	AVALIACAO			DECIMAL(3,1) NOT NULL CHECK(AVALIACAO <= 5 AND AVALIACAO >= 0),
	ID_ANUNCIO			INT NOT NULL,

	CONSTRAINT PK_AVALIACAO_JOGO PRIMARY KEY (NIF_COMPRADOR,NOME_JOGO,ID_ANUNCIO),
	CONSTRAINT FK_AVALIACAO_JOGO_NOME FOREIGN KEY(NOME_JOGO,ID_ANUNCIO) REFERENCES ONLINEGAMES_PLATFORM.JOGO(NOME,ANUNCIO_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_AVALIACAO_JOGO_NIF_COMPRADOR FOREIGN KEY(NIF_COMPRADOR) REFERENCES ONLINEGAMES_PLATFORM.COMPRADOR(NIF)

);

CREATE TABLE ONLINEGAMES_PLATFORM.AVALIACAO_VENDEDOR(
	NIF_COMPRADOR			VARCHAR(30) NOT NULL,
	NIF_VENDEDOR			VARCHAR(30) NOT NULL,
	AVALIACAO_VENDEDOR		DECIMAL(3,1) NOT NULL CHECK(AVALIACAO_VENDEDOR <= 5 AND AVALIACAO_VENDEDOR >= 0),
	data_avaliacao			DATETIME NOT NULL,

	CONSTRAINT PK_AVALIACAO_VENDEDOR PRIMARY KEY (NIF_COMPRADOR,NIF_VENDEDOR,data_avaliacao),
	CONSTRAINT FK_AVALIACAO_VENDEDOR_NIF_COMPRADOR FOREIGN KEY(NIF_COMPRADOR) REFERENCES ONLINEGAMES_PLATFORM.COMPRADOR(NIF),
	CONSTRAINT FK_AVALIACAO_VENDEDOR_NIF_VENDEDOR FOREIGN KEY(NIF_VENDEDOR) REFERENCES ONLINEGAMES_PLATFORM.VENDEDOR(NIF)

);



CREATE TABLE ONLINEGAMES_PLATFORM.FAVORITOS(
	NIF_COMPRADOR			VARCHAR(30) NOT NULL,
	NOME_JOGO				VARCHAR(100) NOT NULL,
	ID_ANUNCIO				INT NOT NULL,
	
	CONSTRAINT PK_FAVORITOS_COMPRADOR PRIMARY KEY (NIF_COMPRADOR,NOME_JOGO,ID_ANUNCIO),
	CONSTRAINT FK_FAVORITOS_NIF_COMPRADOR FOREIGN KEY(NIF_COMPRADOR) REFERENCES ONLINEGAMES_PLATFORM.COMPRADOR(NIF),
	CONSTRAINT FK_FAVORITOS_JOGO_NOME FOREIGN KEY(NOME_JOGO,ID_ANUNCIO) REFERENCES ONLINEGAMES_PLATFORM.JOGO(NOME,ANUNCIO_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	

);

CREATE TABLE ONLINEGAMES_PLATFORM.COMPRA(
	ID_COMPRA INT IDENTITY(1,1) NOT NULL,
	NIF_COMPRADOR			VARCHAR(30) NOT NULL,
	NOME_JOGO				VARCHAR(100) NOT NULL,
	ID_ANUNCIO				INT NOT NULL,
	NR_ARTIGOS				INT ,
	CONSTRAINT PK_COMPRA PRIMARY KEY (ID_COMPRA),
	CONSTRAINT FK_COMPRA_NIF_COMPRADOR FOREIGN KEY(NIF_COMPRADOR) REFERENCES ONLINEGAMES_PLATFORM.COMPRADOR(NIF),
	CONSTRAINT FK_COMPRA_JOGO_NOME FOREIGN KEY(NOME_JOGO,ID_ANUNCIO) REFERENCES ONLINEGAMES_PLATFORM.JOGO(NOME,ANUNCIO_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	
);

CREATE TABLE ONLINEGAMES_PLATFORM.TEM(
	Nome_genero					VARCHAR(30)		NOT NULL,
	NOME_JOGO					VARCHAR(100)		NOT NULL,
	ID_ANUNCIO					INT				NOT NULL,
	
	CONSTRAINT PK_TEM			PRIMARY KEY (Nome_genero,NOME_JOGO,ID_ANUNCIO),
	CONSTRAINT FK_TEM_GENERO	FOREIGN KEY(Nome_genero) REFERENCES ONLINEGAMES_PLATFORM.GENERO(Nome) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_TEM_JOGO		FOREIGN KEY(NOME_JOGO,ID_ANUNCIO) REFERENCES ONLINEGAMES_PLATFORM.JOGO(NOME,ANUNCIO_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	
);

