
--pesquisa de jogo pelo nome
CREATE INDEX idx_jogo_nome ON ONLINEGAMES_PLATFORM.JOGO(NOME);

--pesquisa do nome pela plataforma
CREATE INDEX IDX_JOGO_NOME_PLATAFORMA ON ONLINEGAMES_PLATFORM.JOGO (NOME_PLATAFORMA);

--é calculado a média AVALIACAO_VENDEDOR para um determinado NIF_VENDEDOR
CREATE INDEX IDX_AVALIACAO_VENDEDOR_NIF_VENDEDOR
ON ONLINEGAMES_PLATFORM.AVALIACAO_VENDEDOR (NIF_VENDEDOR);




